steps:
  #- name: 'gcr.io/cloud-builders/npm:node-14.10.1'
  #args: ['i', 'npm@latest', '-g']
  #- name: 'gcr.io/cloud-builders/npm:node-14.10.1'
  #args: ['i', '-g', '@angular/cli@8.3.22']
  #Install node packages
  #- name: 'gcr.io/cloud-builders/npm:node-14.10.1'
  #  args: ['install', '--omit=dev']

  - name: 'python:3.8'
    entrypoint: 'python'
    args: ['./generate_app_yaml.py']
  # Deploy to google cloud app egnine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']